_base_ = './fcn_hr18_1024x1024_20k_gleason_2019_ce_loss.py'
norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    decode_head=dict(
        type='FCNMulLabelHead',
        in_channels=[48, 96, 192, 384],
        channels=sum([48, 96, 192, 384]),
        wei_net_backbone=dict(
            type='HRNet',
            norm_cfg=norm_cfg,
            norm_eval=False,
            extra=dict(
                stage1=dict(
                    num_modules=1,
                    num_branches=1,
                    block='BOTTLENECK',
                    num_blocks=(4, ),
                    num_channels=(64, )),
                stage2=dict(
                    num_modules=1,
                    num_branches=2,
                    block='BASIC',
                    num_blocks=(4, 4),
                    num_channels=(18, 36)),
                stage3=dict(
                    num_modules=4,
                    num_branches=3,
                    block='BASIC',
                    num_blocks=(4, 4, 4),
                    num_channels=(18, 36, 72)),
                stage4=dict(
                    num_modules=3,
                    num_branches=4,
                    block='BASIC',
                    num_blocks=(4, 4, 4, 4),
                    num_channels=(18, 36, 72, 144)))),
        wei_net_conv=dict(
            type='Conv2d',
            in_channels=144,
            out_channels=3,
            kernel_size=3,
            padding=1),
        mul_label_ind=[1, 2, 3],
        final_label_ind=0,
        pretrained='open-mmlab://msra/hrnetv2_w18',
        num_classes=4,
        norm_cfg=norm_cfg,
        loss_decode=dict(type='CrossEntropyLoss'),
        loss_single=dict(type='CrossEntropyLoss'),
        sigma=1,
        loss_step=1000,
        pool_kernel=1))
